// <auto-generated />
using System;
using ExpenseTrackerWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTrackerWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241009154537_SeedCategory")]
    partial class SeedCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTrackerWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2024, 10, 9, 21, 45, 36, 283, DateTimeKind.Local).AddTicks(156),
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2024, 10, 9, 21, 45, 36, 283, DateTimeKind.Local).AddTicks(166),
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDateTime = new DateTime(2024, 10, 9, 21, 45, 36, 283, DateTimeKind.Local).AddTicks(167),
                            Name = "Foods"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
